let strip = neopixel.create(DigitalPin.P0, 15, NeoPixelMode.RGB)
let strip1 = strip.range(0, 3)
let strip2 = strip.range(3, 3)
let strip3 = strip.range(6, 3)
let strip4 = strip.range(9, 3)
let strip5 = strip.range(12, 3)
strip1.showColor(neopixel.colors(NeoPixelColors.Red))
strip2.showColor(neopixel.colors(NeoPixelColors.Blue))
strip3.showColor(neopixel.colors(NeoPixelColors.Green))
strip4.showColor(neopixel.colors(NeoPixelColors.Purple))
strip5.showColor(neopixel.colors(NeoPixelColors.Orange))
