let strip = neopixel.create(DigitalPin.P0, 15, NeoPixelMode.RGB)
let strip1 = strip.range(0, 3)
let strip2 = strip.range(4, 6)
let strip3 = strip.range(7, 9)
let strip4 = strip.range(10, 12)
let strip5 = strip.range(13, 15)
strip1.showColor(neopixel.colors(NeoPixelColors.Red))
strip2.showColor(neopixel.colors(NeoPixelColors.Blue))
strip3.showColor(neopixel.colors(NeoPixelColors.Green))
strip4.showColor(neopixel.colors(NeoPixelColors.Purple))
strip5.showColor(neopixel.colors(NeoPixelColors.Orange))
